# Generated by Django 3.1.3 on 2020-11-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log', '0003_entry_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=1024)),
                ('credatim', models.DateTimeField(auto_now_add=True)),
                ('upddatim', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'promises',
            },
        ),
    ]
